spring:
  profiles:
    active:
    - dev
---
server:
  port: 5001
spring:
  profiles: dev
  application:
    name: config-client5001
---
server:
  port: 5002
spring:
  profiles: test
  application:
    name: config-client5002
---
server:
  port: 5003
spring:
  profiles: product
  application:
    name: config-client5003